server:
  port: 8084
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  data:
    mongodb:
      database: Account
      host: localhost
      port: 27017